0xsequence/marketplace-sdk

src/react/ui/modals/CreateListingModal/_store.ts
src/react/ui/modals/MakeOfferModal/_store.ts
src/react/ui/modals/MakeOfferModal/index.tsx
src/react/ui/modals/SellModal/_store.ts
src/react/ui/modals/_internal/components/priceInput/index.tsx
src/react/ui/modals/_internal/components/priceInput/styles.css.ts

Following is resolved in this PR.
**offering**: Format `pricePerToken` for solving creating offer issue. 
**listing**: We have step with id `'sell'`, and we attempt to check` StepType.createListing` through the steps array, which returns `undefined`.
**selling**: We have this: `order!.feeBreakdown.[0].recipientAddress` feeBreakdown might be `null` which is not what we check for, it keeps throwing error for it.

Refactor transactions

---

packages/sdk/src/react/_internal/api/query-keys.ts
packages/sdk/src/react/hooks/useCheckoutOptions.tsx
packages/sdk/src/react/hooks/useCountOfCollectables.tsx
packages/sdk/src/react/hooks/useCurrencies.tsx
packages/sdk/src/react/hooks/useListListingsForCollectible.tsx
packages/sdk/src/react/ui/modals/CreateListingModal/index.tsx
packages/sdk/src/react/ui/modals/TransferModal/_views/enterWalletAddress/index.tsx

Add a hook for getting list of listings of a collectible

Hook list collectible listings

---

playgrounds/react-vite/src/tabs/Collectable.tsx

fix: price of orders, table titles, disable next cta properly

---

packages/sdk/src/react/ui/components/_internals/action-button/ActionButton.tsx

We didn't return the button, that's why it looked blank. There shouldn't be a leakage case

Fix return action button for buy

---

packages/sdk/package.json
packages/sdk/src/react/ui/components/_internals/custom-select/CustomSelect.tsx
packages/sdk/src/react/ui/components/collectible-card/CollectibleCard.tsx
packages/sdk/src/react/ui/components/collectible-card/Footer.tsx
packages/sdk/src/react/ui/modals/_internal/components/currencyOptionsSelect/index.tsx
packages/sdk/src/styles/index.ts
packages/sdk/tsup.config.ts
playgrounds/react-vite/src/main.tsx
playgrounds/react-vite/src/tabs/Collectables.tsx

* Export styles of collectible card
* Show ERC-1155 badge if the collectible is not owned and is type of 1155.
* Set absolute position to offer bell icon button

Fix styles of collectiblecard

---

playgrounds/react-vite/src/lib/abis/seaport.ts
playgrounds/react-vite/src/tabs/Debug.tsx

- Adds seaport abi
- Function to get all function signatures of selected abi

Debug seaport

---

packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts
packages/sdk/src/react/_internal/transaction-machine/useTransactionMachine.ts
packages/sdk/src/react/hooks/useCurrencies.tsx
packages/sdk/src/react/hooks/useCurrencyBalance.tsx
packages/sdk/src/react/ui/components/collectible-card/Footer.tsx
packages/sdk/src/react/ui/modals/_internal/components/currencyOptionsSelect/index.tsx

Keep cards same height by adding a `Not listed yet` text

Refactor collectible card

---

packages/sdk/src/react/hooks/useCurrencies.tsx
packages/sdk/src/react/hooks/useCurrencyOptions.tsx
packages/sdk/src/react/ui/components/collectible-card/CollectibleCard.tsx
packages/sdk/src/react/ui/modals/BuyModal/index.tsx
packages/sdk/src/react/ui/modals/MakeOfferModal/index.tsx
packages/sdk/src/react/ui/modals/SellModal/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/currencyOptionsSelect/index.tsx
packages/sdk/src/utils/_internal/error/transaction.ts

Pass `currencyOptions` from `marketplaceConfig` to `useCurrencies` to avoid hydration issues as fetching config in select util.

Fix - Marketplace Config on useCurrencies

---

packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts
packages/sdk/src/react/_internal/transaction-machine/useTransactionMachine.ts
packages/sdk/src/react/hooks/useCreateListing.tsx
packages/sdk/src/react/hooks/useCurrencies.tsx
packages/sdk/src/react/hooks/useMakeOffer.tsx
packages/sdk/src/react/ui/modals/CreateListingModal/index.tsx
packages/sdk/src/react/ui/modals/MakeOfferModal/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/currencyOptionsSelect/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/transaction-footer/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionPreview/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionPreview/useTransactionPreviewTitle.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/store.ts
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/util/getMessage.ts
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/util/getTitle.ts
packages/sdk/src/utils/_internal/error/transaction.ts

This PR makes us able to make offers and create listings via Reservoir.

Refactor signature execution to handle reservoir orders

---

packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts
packages/sdk/src/react/hooks/useCreateListing.tsx
packages/sdk/src/react/hooks/useMakeOffer.tsx
packages/sdk/src/react/hooks/useSell.tsx
packages/sdk/src/react/ui/modals/MakeOfferModal/index.tsx
packages/sdk/src/react/ui/modals/SellModal/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/actionModal/ActionModal.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionDetails/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/index.tsx

https://github.com/user-attachments/assets/b769af40-af5e-4c76-8ddd-8fff63841275

Refactor ctas while transaction processing

---

packages/sdk/src/react/_internal/transaction-machine/useTransactionMachine.ts
packages/sdk/src/react/ui/modals/CreateListingModal/index.tsx
packages/sdk/src/react/ui/modals/MakeOfferModal/index.tsx

Problem was about triggering useEffect that handles refreshing steps. 
Beside this, I updated `CreateListingModal`to use `handleStepExecution` instead calling the util that creates listing, which fixes changes state of main CTA to pending while transaction is being executed.

Fix make offer loading steps

---

playgrounds/react-vite/src/components/collectible/Actions.tsx
playgrounds/react-vite/src/components/collectible/CollectibleDetails.tsx
playgrounds/react-vite/src/components/collectible/ListingsTable.tsx
playgrounds/react-vite/src/components/collectible/OffersTable.tsx
playgrounds/react-vite/src/components/collectible/OrdersTable.tsx
playgrounds/react-vite/src/components/collectible/OrdersTableRow.tsx
playgrounds/react-vite/src/components/collectible/index.ts
playgrounds/react-vite/src/tabs/Collectable.tsx

Separate into different components for improving maintainability and readability of playground vite-react project.

Refactor playground collectible tab

---

packages/sdk/src/react/ui/modals/_internal/components/switchChainModal/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/switchChainModal/styles.css.ts
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/index.tsx
playgrounds/react-vite/src/components/collectible/ListingsTable.tsx

For resolving [switch chain modal overlaps main modals](https://github.com/0xsequence/issue-tracker/issues/3957)

Fix switch chain modal overlaps main modal

---

playgrounds/react-vite/package.json
playgrounds/react-vite/src/App.tsx
playgrounds/react-vite/src/components/Navigation.tsx
playgrounds/react-vite/src/components/collectible/ListingsTable.tsx
playgrounds/react-vite/src/lib/MarketplaceContext.tsx
playgrounds/react-vite/src/lib/routes.ts
playgrounds/react-vite/src/main.tsx
playgrounds/react-vite/src/tabs/Collectables.tsx
playgrounds/react-vite/src/tabs/Collections.tsx
pnpm-lock.yaml

Missing queries when switching tabs turn out still there. This PR fixes it and is for better UX.
https://github.com/user-attachments/assets/cdb4bc52-f5e1-411b-88e4-7d3a81a6a6f3

Refactor playground implement navigation

---

packages/sdk/src/react/_internal/types.ts
packages/sdk/src/react/ui/modals/CreateListingModal/hooks/useCreateListing.tsx
packages/sdk/src/react/ui/modals/MakeOfferModal/hooks/useGetTokenApproval.tsx
packages/sdk/src/react/ui/modals/_internal/components/expirationDateSelect/index.tsx

https://github.com/0xsequence/issue-tracker/issues/3998
It used to set current date with time if _today_ is selected. This PR is for fixing it by setting date to end of the day the user is on, 23:59:59

3998 - Fix expiration date end of day

---

packages/sdk/src/react/hooks/useCurrencies.tsx
packages/sdk/src/react/ui/components/_internals/action-button/ActionButton.tsx
packages/sdk/src/react/ui/components/collectible-card/CollectibleCard.tsx
packages/sdk/src/react/ui/modals/CreateListingModal/hooks/useCreateListing.tsx
packages/sdk/src/react/ui/modals/CreateListingModal/store.ts
packages/sdk/src/react/ui/modals/MakeOfferModal/hooks/useGetTokenApproval.tsx
packages/sdk/src/react/ui/modals/MakeOfferModal/hooks/useMakeOffer.tsx
packages/sdk/src/react/ui/modals/MakeOfferModal/store.ts
playgrounds/react-vite/src/lib/MarketplaceContext.tsx
playgrounds/react-vite/src/lib/Settings.tsx

- **Use destination marketplace for listings**
- **Add default orderbook to playground**

Fix destination marketplace for offers

---

packages/sdk/src/utils/__tests__/address.test.ts
packages/sdk/src/utils/__tests__/date.test.ts
packages/sdk/src/utils/__tests__/get-public-rpc-client.test.ts
packages/sdk/src/utils/__tests__/getMarketplaceDetails.test.ts
packages/sdk/src/utils/__tests__/price.test.ts
packages/sdk/src/utils/get-public-rpc-client.ts
packages/sdk/vitest.config.js

Write tests for:
packages/sdk/src/utils/address.ts
packages/sdk/src/utils/date.ts
packages/sdk/src/utils/get-public-rpc-client.ts
packages/sdk/src/utils/getMarketplaceDetails.ts
packages/sdk/src/utils/price.ts

Feat - Tests for utils at `packages/sdk/src/utils`

---

packages/sdk/src/react/ui/modals/MakeOfferModal/__tests__/Modal.test.tsx
packages/sdk/src/react/ui/modals/_internal/components/priceInput/__tests__/index.test.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionPreview/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/__tests__/TransactionStatusModal.test.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/__tests__/utils.test.ts
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/index.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/util/getMessage.ts

- Complete test coverage for `getFormattedType` including verb variations
- Comprehensive tests for `getTransactionStatusModalMessage` covering all transaction states
- Test cases for `getTransactionStatusModalTitle` with various scenarios
- Validation of `getTransactionStatusModalSpinnerTitle` for all status types
- Transaction type formatting (transfer, listing, buy, sell, cancel, offer)
- Status-specific messages and titles
- Edge cases like undefined transaction types
- Special handling for offers with price information
- Order ID scenarios
- Timeout and failure states
- Modal visibility control (show/hide)
- Transaction state transitions:
- Processing state display
- Success state handling
- Failure state management
- Timeout state handling
- Callback execution validation:
- Success …

Test/ Transaction status modal

---

packages/sdk/src/react/hooks/options/__mocks__/marketplaceConfig.msw.ts
packages/sdk/src/react/hooks/options/__tests__/marketplaceConfigOptions.test.tsx
packages/sdk/src/types/marketplace-config.ts

- Implemented MSW (Mock Service Worker) handlers to simulate marketplace configuration API endpoints
- Added comprehensive test suite for `marketplaceConfigOptions`
- Created mock data and debug utilities for testing purposes
- Created handlers for successful config and styles fetching
- Added error handlers to test failure scenarios
- Implemented debug logging functionality for development purposes
- Structured mock data to match production marketplace configuration
- Basic successful config and styles fetching
- Custom environment and dev access key handling
- Error handling for non-existent projects
- Network error handling for style fetching
- Query key and function validation

Mock marketplace config options

---

playgrounds/react-vite/src/tabs/Collections.tsx

NetworkPill component for Collections tab

---

playgrounds/react-vite/src/components/collectible/tables/CurrencyCell.tsx
playgrounds/react-vite/src/components/collectible/tables/ListingsTable.tsx
playgrounds/react-vite/src/components/collectible/tables/OffersTable.tsx
playgrounds/react-vite/src/tabs/Collectable.tsx

Add Quantity column that would be shown for ERC1155 collections.
Add currency image.

Playground table improvements

---

package.json
packages/sdk/src/react/_internal/api/query-keys.ts
packages/sdk/src/react/hooks/index.ts
packages/sdk/src/react/hooks/useCollectionBalanceDetails.tsx
packages/sdk/src/react/ui/modals/BuyModal/hooks/useBuyCollectable.ts
packages/sdk/src/react/ui/modals/TransferModal/_views/enterWalletAddress/useHandleTransfer.tsx
playgrounds/react-vite/src/components/collectible/Actions.tsx
playgrounds/react-vite/src/tabs/Collectable.tsx
playgrounds/react-vite/src/tabs/Debug.tsx
pnpm-lock.yaml
pnpm-workspace.yaml

https://github.com/0xsequence/issue-tracker/issues/4177

4177 - Fix queries issues after purchase item

---

packages/sdk/src/react/hooks/index.ts
packages/sdk/src/react/hooks/useAutoSelectFeeOption.tsx
packages/sdk/src/react/hooks/useCancelOrder.tsx
playgrounds/react-vite/src/components/collectible/tables/ListingsTable.tsx
playgrounds/react-vite/src/components/collectible/tables/OffersTable.tsx

https://github.com/0xsequence/issue-tracker/issues/4063
https://github.com/user-attachments/assets/21aa6203-04e9-4891-b2dd-8c339006221a

4063 - Auto select fee option waas

---

packages/sdk/src/react/_internal/api/__mocks__/metadata.msw.ts
packages/sdk/src/react/_internal/test/mocks/publicClient.ts
packages/sdk/src/react/hooks/__tests__/useCountOfCollectables.test.tsx
packages/sdk/src/react/hooks/__tests__/useCountOffersForCollectible.test.tsx
packages/sdk/src/react/hooks/__tests__/useCurrencies.test.tsx
packages/sdk/src/react/hooks/__tests__/useCurrency.test.tsx
packages/sdk/src/react/hooks/__tests__/useCurrencyBalance.test.tsx
packages/sdk/src/react/hooks/__tests__/useFloorOrder.test.tsx
packages/sdk/src/react/hooks/__tests__/useHighestOffer.test.tsx
packages/sdk/src/react/hooks/__tests__/useListBalances.test.tsx
packages/sdk/src/react/hooks/__tests__/useListCollectibleActivities.test.tsx
packages/sdk/src/react/hooks/__tests__/useListCollectibles.test.tsx
packages/sdk/src/react/hooks/__tests__/useListCollectionActivities.test.tsx
packages/sdk/src/react/hooks/__tests__/useListCollections.test.tsx
packages/sdk/src/react/hooks/__tests__/useListListingsForCollectible.test.tsx
packages/sdk/src/react/hooks/__tests__/useListOffersForCollectible.test.tsx
packages/sdk/src/react/hooks/__tests__/useLowestListing.test.tsx
packages/sdk/src/react/hooks/__tests__/useMarketplaceConfig.test.tsx
packages/sdk/src/react/hooks/__tests__/useRoyaltyPercentage.test.tsx
packages/sdk/src/react/hooks/useGenerateBuyTransaction.tsx
packages/sdk/src/react/hooks/useListCollectibleActivities.tsx
packages/sdk/src/react/hooks/useListCollectibles.tsx
packages/sdk/src/react/hooks/useListCollectionActivities.tsx

ℹ️ I will be writing tests for other hooks on a separate PR in order to make PRs reviewable.

Tests for hooks 2

---

packages/sdk/src/react/_internal/api/__mocks__/metadata.msw.ts
packages/sdk/src/react/_internal/test-utils.tsx
packages/sdk/src/react/_internal/test/setup.ts
packages/sdk/src/react/hooks/__tests__/useFilters.test.tsx
packages/sdk/src/react/hooks/options/__mocks__/marketplaceConfig.msw.ts
packages/sdk/src/react/ui/modals/BuyModal/hooks/__tests__/useBuyCollectable.test.tsx
packages/sdk/src/react/ui/modals/BuyModal/hooks/__tests__/useFees.test.tsx
packages/sdk/src/react/ui/modals/BuyModal/modals/__tests__/Modal1155.test.tsx
packages/sdk/src/react/ui/modals/SellModal/hooks/useGetTokenApproval.tsx
packages/sdk/src/react/ui/modals/_internal/components/currencyOptionsSelect/__tests__/index.test.tsx

This PR focuses on improving test reliability and fixing failed tests across several components ✅. 
The changes include:
- Improved async handling in tests using `waitFor`
- Added more robust currency selection verification
- Enhanced test coverage for currency reload scenarios
- Fixed mock implementations for hooks
- Added comprehensive test coverage for chain mismatch scenarios
- Improved price calculation validations
- Added wallet mock utilities
- Enhanced test organization and readability
- Added `skipToken` support in `useGetTokenApproval` to prevent unnecessary API calls
- Improved error handling and type safety
- Fixed query conditional execution
- Added property filters for metadata testing
- Updated currency mock data structure
- Improved test setup configuration

Fix Failed Tests and Test Improvements

---

packages/sdk/src/react/ui/modals/_internal/components/actionModal/ErrorModal.tsx

https://github.com/0xsequence/issue-tracker/issues/4204

4204 - Wrap message with Text component from design-system

---

packages/sdk/src/react/hooks/useFilters.tsx

https://github.com/0xsequence/issue-tracker/issues/4243#issuecomment-2679008570

handle empty exclusions and filter order

---

packages/sdk/src/react/hooks/__tests__/useListCollectiblesPaginated.test.tsx
packages/sdk/src/react/hooks/index.ts
packages/sdk/src/react/hooks/useListCollectiblesPaginated.tsx
playgrounds/react-vite/src/lib/MarketplaceContext.tsx
playgrounds/react-vite/src/lib/Settings.tsx
playgrounds/react-vite/src/tabs/Collectables.tsx
playgrounds/react-vite/src/tabs/components/InfiniteScrollView.tsx
playgrounds/react-vite/src/tabs/components/PaginatedView.tsx

Implement `useListCollectiblesPaginated` hook and use it on playground.
https://github.com/user-attachments/assets/69fc15b4-087a-4449-8e0f-7583c0609cfb

Paginated variant of use list collectibles

---

packages/sdk/src/react/ui/modals/_internal/components/priceInput/__tests__/index.test.tsx
packages/sdk/src/react/ui/modals/_internal/components/priceInput/index.tsx

[Ticket](https://github.com/0xsequence/issue-tracker/issues/4287)
When changing currencies with different decimal places in the price input, the raw amount wasn't being properly adjusted to account for the decimal difference. This caused incorrect price calculations when generating listing transactions.
- Added tracking of previous currency decimals with useRef
- Added useEffect to detect currency decimal changes
- Recalculate raw amount when currency decimals change
- Added test case to verify the fix works correctly

4287 - fix: adjust price amount when changing currency with different decimals

---

packages/sdk/src/react/ui/components/collectible-card/Footer.tsx
packages/sdk/src/react/ui/components/collectible-card/styles.css.ts

[Issue](https://github.com/0xsequence/issue-tracker/issues/4348)
price: 0.00000001 USDC
price: 1,000,000,000,000 USDC
price: 100,000,000 USDC

4348 - improve price formatting on Footer component

---

packages/sdk/src/react/ui/modals/CreateListingModal/Modal.tsx
packages/sdk/src/react/ui/modals/SellModal/Modal.tsx
packages/sdk/src/react/ui/modals/_internal/components/transactionDetails/index.tsx

[Issue](https://github.com/0xsequence/issue-tracker/issues/4350)

4350 - fix: don't take marketplace fee into account if its listing modal

---

packages/sdk/package.json
packages/sdk/src/index.css
packages/sdk/src/react/ui/components/_internals/custom-select/CustomSelect.tsx
packages/sdk/src/react/ui/components/_internals/custom-select/__tests__/CustomSelect.test.tsx
packages/sdk/src/react/ui/modals/_internal/components/currencyOptionsSelect/__tests__/index.test.tsx
packages/sdk/src/react/ui/modals/_internal/components/currencyOptionsSelect/index.tsx
pnpm-lock.yaml
pnpm-workspace.yaml

Use `DropdownMenu` components from design-system instead.
https://github.com/user-attachments/assets/90ecd54a-23b9-441c-a4e8-3c2f1641999d

Drop Radix-ui/react-select, use design-system instead

---

packages/sdk/src/index.css
packages/sdk/src/react/ui/components/collectible-card/CollectibleCard.tsx
playgrounds/react-vite/src/App.tsx
playgrounds/react-vite/src/tabs/components/GridContainer.tsx
playgrounds/react-vite/src/tabs/components/InfiniteScrollView.tsx

[Ticket](https://github.com/0xsequence/issue-tracker/issues/4417)
https://github.com/user-attachments/assets/480b88de-bc0c-44d6-868a-7ee8eb2d55f5

Collectible card dynamic width

---

playgrounds/shared/src/components/ordersTable/_components/Action.tsx
playgrounds/shared/src/components/ordersTable/_components/TableRow.tsx
sdk/src/react/ui/modals/BuyModal/modals/Modal1155.tsx

[Ticket](https://github.com/0xsequence/issue-tracker/issues/4406)
Improve price formatting using dnum.

Refactor ERC1155QuantityModal total price calculation

---

playgrounds/next/src/app/(marketplace)/collectible/page.tsx
playgrounds/next/src/app/(marketplace)/collectibles/components/InfiniteScrollView.tsx
playgrounds/next/src/app/(marketplace)/collectibles/components/PaginatedView.tsx
playgrounds/react-vite/src/tabs/Collectable.tsx
playgrounds/react-vite/src/tabs/components/InfiniteScrollView.tsx
playgrounds/react-vite/src/tabs/components/PaginatedView.tsx
playgrounds/shared/src/index.ts
playgrounds/shared/src/util.ts
sdk/src/react/ui/components/collectible-card/CollectibleCard.tsx
sdk/src/react/ui/components/collectible-card/Footer.tsx

Pass button click event through prop of `CollectibleCard` and use it on playgrounds.
https://github.com/user-attachments/assets/8e03e7b7-befe-4f94-a3f5-c014d5897013

Fix logic of offer bell button

---

sdk/src/react/ui/modals/CreateListingModal/Modal.tsx
sdk/src/react/ui/modals/CreateListingModal/hooks/useTransactionSteps.tsx
sdk/src/react/ui/modals/CreateListingModal/store.ts
sdk/src/react/ui/modals/TransferModal/_views/enterWalletAddress/index.tsx
sdk/src/react/ui/modals/TransferModal/index.tsx
sdk/src/react/ui/modals/_internal/components/actionModal/ActionModal.tsx
sdk/src/react/ui/modals/_internal/components/expirationDateSelect/index.tsx
sdk/src/react/ui/modals/_internal/components/floorPriceText/index.tsx
sdk/src/react/ui/modals/_internal/components/priceInput/index.tsx
sdk/src/react/ui/modals/_internal/components/quantityInput/index.tsx
sdk/src/react/ui/modals/_internal/components/selectWaasFeeOptions/_components/ActionButtons.tsx
sdk/src/react/ui/modals/_internal/components/selectWaasFeeOptions/index.tsx
sdk/src/react/ui/modals/_internal/components/transaction-footer/index.tsx

[Ticket](https://github.com/0xsequence/issue-tracker/issues/4669)
https://github.com/user-attachments/assets/b64a730a-72a4-4ccd-9840-64b68fc7abbc
Cases to test: 
✅ WaaS + testnet collection + creating listing
✅ WaaS + mainnet collection + creating listing
✅ Universal wallet + testnet collection + creating listing
✅ Universal wallet + mainnet collection + creating listing
✅ Metamask + testnet collection + token approval + creating listing
✅ Metamask + mainnet collection + token approval + creating listing

Refactor listing flow with waas

---

sdk/src/react/ui/modals/MakeOfferModal/Modal.tsx
sdk/src/react/ui/modals/MakeOfferModal/hooks/useTransactionSteps.tsx
sdk/src/react/ui/modals/MakeOfferModal/store.ts
sdk/src/react/ui/modals/_internal/components/transactionStatusModal/index.tsx

Cases to test:
✅ WaaS + testnet collection + making offer
✅ WaaS + mainnet collection + making offer
✅ Universal wallet + testnet collection + making offer
✅ Universal wallet + mainnet collection + making offer
✅ Metamask + testnet collection + token approval + making offer
✅ Metamask + mainnet collection + token approval + making offer

Refactor offer flow with waas

---

sdk/src/react/ui/modals/SellModal/Modal.tsx
sdk/src/react/ui/modals/SellModal/hooks/useTransactionSteps.tsx
sdk/src/react/ui/modals/SellModal/store.ts

Cases to test:
✅ WaaS + testnet collection + sell
✅ WaaS + mainnet collection + sell
✅ Universal wallet + testnet collection + sell
✅ Universal wallet + mainnet collection + sell
✅ Metamask + testnet collection + sell
✅ Metamask + mainnet collection + sell

Refactor sell flow with waas

---

sdk/src/react/ui/modals/_internal/components/actionModal/ActionModal.tsx
sdk/src/react/ui/modals/_internal/components/selectWaasFeeOptions/index.tsx

[Ticket](https://github.com/0xsequence/issue-tracker/issues/4708)

fix: add text color classnames

---

sdk/src/react/ui/modals/CreateListingModal/__tests__/Modal.test.tsx

update modal rendering scenarios, improve wallet handling, and verify button states based on approval steps.

Enhance `CreateListingModal` tests

---

sdk/src/react/ui/modals/_internal/components/selectWaasFeeOptions/__tests__/ActionButtons.test.tsx
sdk/src/react/ui/modals/_internal/components/selectWaasFeeOptions/__tests__/BalanceIndicator.test.tsx
sdk/src/react/ui/modals/_internal/components/selectWaasFeeOptions/__tests__/SelectWaasFeeOptions.test.tsx

Tests include:
•	✅ Visibility conditions (show/hide based on internal state)
•	✅ Network type handling (skip on testnet)
•	✅ Loading state rendering
•	✅ Fee options display
•	✅ Proper rendering of all component states
----
Tests include:
•	✅ Correct rendering of buttons
•	✅ Click event handling
•	✅ Disabled state behavior
•	✅ Token symbol display
•	✅ Loading state UI
----
Tests include:
•	✅ Display of insufficient balance warning
•	✅ Display of sufficient balance state
•	✅ Graceful handling of undefined or missing balances

Tests of SelectWaasFeeOptions

---

sdk/src/react/ui/modals/SellModal/__tests__/Modal.test.tsx

refactor test structure, add scenarios for approval steps, and improve mock implementations

Tests of SellModal

---

playgrounds/next/src/app/(marketplace)/collectible/page.tsx
playgrounds/next/src/app/(marketplace)/collectibles/components/InfiniteScrollView.tsx
playgrounds/next/src/app/(marketplace)/collectibles/components/PaginatedView.tsx
playgrounds/react-vite/src/tabs/Collectable.tsx
playgrounds/react-vite/src/tabs/Collections.tsx
playgrounds/react-vite/src/tabs/Inventory.tsx
playgrounds/react-vite/src/tabs/components/InfiniteScrollView.tsx
playgrounds/react-vite/src/tabs/components/PaginatedView.tsx
sdk/src/react/ui/components/collectible-card/CollectibleAsset.tsx
sdk/src/react/ui/components/collectible-card/CollectibleCard.tsx
sdk/src/react/ui/components/collectible-card/__tests__/CollectibleAsset.test.tsx
sdk/src/react/ui/components/collectible-card/__tests__/CollectibleCard.test.tsx
sdk/src/react/ui/components/collectible-card/__tests__/Footer.test.tsx

- Verifies image rendering with proper loading states and fallback handling
- Tests video content playback with appropriate controls and loading states
- Ensures HTML content in iframes is rendered securely with proper sandboxing
- Renders collectible information correctly
- Handles name truncation based on content length
- Validates price formatting for:
- Normal price display
- Overflow and underflow cases
- Displays "Not listed yet" when no listing price is available
- Differentiates token balance display between ERC721 and ERC1155
- Confirms proper rendering of collectible details
- Validates skeleton component behavior during loading states
- Tests user interaction callbacks for both the collectible and its action buttons

Add test coverage for `CollectibleCard` components

---

sdk/src/react/hooks/__tests__/useCurrencyBalance.test.tsx
sdk/src/react/ui/modals/_internal/components/switchChainModal/__tests__/SwitchChainModal.test.tsx
sdk/src/react/ui/modals/_internal/components/switchChainModal/index.tsx

Refactor skipped tests

---

sdk/src/react/_internal/wallet/__tests__/wallet.test.ts
sdk/src/react/_internal/wallet/wallet.ts
sdk/src/react/hooks/useCancelTransactionSteps.tsx
sdk/src/react/ui/modals/CreateListingModal/hooks/useTransactionSteps.tsx
sdk/src/react/ui/modals/MakeOfferModal/hooks/useTransactionSteps.tsx
sdk/src/react/ui/modals/SellModal/hooks/useTransactionSteps.tsx

[Ticket](https://github.com/0xsequence/issue-tracker/issues/4906)
- Improved error handling in the wallet module to differentiate user-rejected requests.
- Added checks for BaseError and ViemUserRejectedRequestError to provide clearer feedback on transaction failures.
- Updated the useTransactionSteps hook to gracefully handle UserRejectedRequestError without triggering onError callbacks.

Enhance error handling in wallet transactions

---

playgrounds/react-vite/src/components/collectible/CollectibleDetails.tsx
playgrounds/react-vite/src/tabs/Collectable.tsx
pnpm-lock.yaml
pnpm-workspace.yaml
sdk/package.json
sdk/src/react/ui/components/ModelViewer.tsx
sdk/src/react/ui/components/collectible-card/CollectibleCard.tsx
sdk/src/react/ui/components/collectible-card/__tests__/CollectibleAsset.test.tsx
sdk/src/react/ui/components/collectible-card/collectible-asset/CollectibleAsset.tsx
sdk/src/react/ui/components/collectible-card/collectible-asset/utils.ts
sdk/src/react/ui/components/collectible-card/index.ts
sdk/src/react/ui/index.ts
sdk/src/utils/fetchContentType.ts

New look of `CollectibleAsset`:
```
<CollectibleAsset
name={collectible.name}
assets={[
collectible.video, // if this is defined, renders the video
collectible.animation_url, // if this is defined, and collectible.video is not,  renders the animation
collectible.image, // if nothing above but this is defined, render the image
]}
className="h-[300px] w-[300px] overflow-hidden rounded-xl"
/>
```

Export collectible asset

---

pnpm-lock.yaml
pnpm-workspace.yaml
sdk/src/react/_internal/api/services.ts
sdk/src/react/ui/modals/BuyModal/hooks/usePaymentModalParams.ts
sdk/src/types/sdk-config.ts

-Enabled fetching of the transak contract id, enable transak integration
-The transak api key field will become optional in an upcoming version of web-sdk

added transak contract config to openSelectModal params

---

playgrounds/shared/src/store/store.ts
sdk/src/react/hooks/useList721ShopCardData.ts
sdk/src/react/ui/components/marketplace-collectible-card/Footer.tsx
sdk/src/react/ui/components/marketplace-collectible-card/MarketplaceCollectibleCard.tsx

Identify quantity remaining of a 721 sale collectible by owner of it, if it's owned by some address, `it's out-of-stock`. If it's not, `available quantity of it is 1`

Quantity remaining of 721 sale card

---

playgrounds/next/src/app/(marketplace)/collectibles/components/InfiniteScrollView.tsx
playgrounds/react-vite/src/tabs/components/CollectibleCardRenderer.tsx
sdk/src/react/ui/components/marketplace-collectible-card/Footer.tsx
sdk/src/react/ui/components/marketplace-collectible-card/MarketplaceCollectibleCard.tsx
sdk/src/react/ui/components/marketplace-collectible-card/__tests__/Footer.test.tsx
sdk/src/react/ui/components/marketplace-collectible-card/__tests__/MarketplaceCollectibleCard.test.tsx
sdk/src/react/ui/modals/BuyModal/ERC1155QuantityModal.tsx
sdk/src/react/ui/modals/_internal/components/quantityInput/index.tsx

* Hide sales that are not started yet
* Enhance supply display with unlimited supply calculation

Footer unlimited supply cap

---

sdk/src/react/hooks/__tests__/useListMarketCardData.test.tsx

- Introduced comprehensive tests for the useListMarketCardData hook, covering various scenarios including fetching collectibles and balances, handling disconnected wallet states, API error management, and filtering options.
- Implemented tests for pagination and combined filters to ensure robust functionality.
- Utilized MSW for mocking API responses to simulate different states and validate the hook's behavior under various conditions.
- Ensured that the hook correctly handles collectible click callbacks and prioritizes owner actions when specified.

Add tests for useListMarketCardData hook

---

sdk/src/react/_internal/api/laos-api.ts
sdk/src/react/queries/balanceOfCollectible.ts
sdk/src/react/queries/inventory.ts
sdk/src/react/queries/listBalances.ts

Fix Laos `getTokenBalances` params and body of it

---

playgrounds/shared/src/components/collectible/CollectibleDetails.tsx
playgrounds/shared/src/components/collectible/actions/Actions.tsx
playgrounds/shared/src/components/collectible/actions/MarketActions.tsx
playgrounds/shared/src/components/collectible/actions/ShopActions.tsx
playgrounds/shared/src/components/collectible/index.ts
playgrounds/shared/src/components/pages/CollectiblePageController.tsx

separate actions that a user can take on market and shop collectible details page

sale collectible details

---

sdk/src/react/ui/components/marketplace-collectible-card/Footer.tsx

https://github.com/user-attachments/assets/30bf21bc-62e4-434c-8711-b5bf75f8d66f

Add free price display in Footer component

---

.github/workflows/pre-release-deploy.yml

Automates preview releases and pushed them to a branch named pre-release
https://github.com/0xsequence/issue-tracker/issues/5513

Add pre release publish script

---

playgrounds/shared/src/components/pages/ShopContent.tsx
sdk/src/react/hooks/data/primary-sales/useList721ShopCardData.tsx

[Issue](https://github.com/0xsequence/issue-tracker/issues/5490#issuecomment-3158458644)
Improve `useList721ShopCardData` to loop through all pages of `tokenSupplies` with `includeMetadata:true` so we don't need to use `useSearchTokenMetadata` no more. 
`ListPrimarySaleItems` endpoint does returns minted tokens as well, which is not correct. `tokenSupplies` is always up to date with minted tokens, so 
🎥 Tokens with token ids 75, 76, 77, 78, 79 are minted and `ListPrimarySaleItems` actually returns these tokens. But I filtered out them, so internally converted data from `ListPrimarySaleItems` to be unminted (available) tokens. Applied pagination accordingly.
✅ Consuming `useList721ShopCardData` is now more simple.
https://github.com/user-attachments/assets/6191b427-eccb-472f-ae07-14e1af0478 …

Simplify minted tokens calculation 721 sale cards

---

sdk/src/react/ui/modals/BuyModal/components/ERC1155QuantityModal.tsx
sdk/src/react/ui/modals/_internal/components/quantityInput/__tests__/index.test.tsx
sdk/src/react/ui/modals/_internal/components/quantityInput/index.tsx

This PR updates the logic for handling local quantity initialization, ensuring it respects the minimum quantity allowed based on the defined decimal precision. It also adjusts the calculations for maximum and minimum quantities to correctly account for decimals, enabling accurate increment and decrement operations. These changes ensure consistent behavior when dealing with fractional quantities.

1155 QuantityModal : Adjust Quantity to Respect Decimal Precision and Minimum Constraints

---

pnpm-lock.yaml
sdk/package.json

TS-down have changed some glob patters in the latest version, breaking our build

Downgrade tsdown

---

sdk/src/react/ui/components/marketplace-collectible-card/Footer.tsx
sdk/src/react/ui/components/marketplace-collectible-card/components/BaseCard.tsx
sdk/src/react/ui/components/marketplace-collectible-card/types.ts
sdk/src/react/ui/components/marketplace-collectible-card/variants/MarketCard.tsx
sdk/src/react/ui/components/marketplace-collectible-card/variants/ShopCard.tsx

https://github.com/0xsequence/issue-tracker/issues/5686
- Updated Footer component to utilize hooks for fetching lowest listing and currency data.
- Removed deprecated props for lowest listing price and currency, replacing them with derived values from hooks.
- Modified BaseCard component to use 'cardLoading' instead of 'isLoading' for better clarity.
- Adjusted MarketCard component to pass new props to Footer and removed unnecessary loading logic.

Refactor Footer and BaseCard components to integrate lowest listing data

---

sdk/.changeset/cruel-fans-remain.md
sdk/src/react/hooks/data/orders/useListOffersForCollectible.tsx
sdk/src/react/queries/index.ts
sdk/src/react/queries/listOffersForCollectible.ts

- Updated the parameters to include optional filtering and pagination options.
- Improved documentation with detailed JSDoc comments for better usability and understanding.
- Created a new query file for listOffersForCollectible, encapsulating the fetching logic and query options.
- Ensured backward compatibility for sorting parameters during pagination.

Move sort outside page object use list offers for collectible

---

sdk/src/react/ui/modals/_internal/components/priceInput/index.tsx

https://github.com/0xsequence/issue-tracker/issues/5765

Refactor PriceInput component styles

---

pnpm-lock.yaml
sdk/src/react/ui/modals/BuyModal/components/BuyModalContent.tsx
sdk/src/react/ui/modals/BuyModal/components/FallbackPurchaseUI.tsx
sdk/src/react/ui/modals/BuyModal/hooks/useBuyModalData.ts
sdk/src/styles/styles.ts

Fallback buy modal UI fix

---

sdk/src/react/ui/modals/BuyModal/components/TrailsCss.ts

https://github.com/user-attachments/assets/6d237619-1b28-4a6a-ad09-9517ff9e51c1

remove opacity from --trails-bg-secondary and replace with matching color

---

sdk/src/react/ui/modals/BuyModal/components/FallbackPurchaseUI.tsx
sdk/src/react/ui/modals/BuyModal/components/FallbackPurchaseUISkeleton.tsx
sdk/src/react/ui/modals/BuyModal/hooks/useBuyModalData.ts
sdk/src/react/ui/modals/BuyModal/hooks/useHasSufficientBalance.ts

https://github.com/user-attachments/assets/e4f87b3e-76b0-44a3-af08-0f91a1c5dc55
https://github.com/user-attachments/assets/43aa29cc-2e29-4691-b9e1-a6ab50be632a

Trails shop fallback UI

---

playgrounds/shared/src/components/pages/CollectiblePageController.tsx
playgrounds/shared/src/components/pages/MarketContent.tsx
sdk/src/react/ui/modals/MakeOfferModal/Modal.tsx
sdk/src/react/ui/modals/_internal/components/priceInput/index.tsx

https://github.com/user-attachments/assets/abd95b4f-a9fa-4ee4-955a-d697193c24b0

Opensea lowest order price criteria

---

sdk/src/react/ui/modals/CreateListingModal/Modal.tsx

- Modified the orderbookKind prop to default to collectionOrderbookKind if not provided, ensuring better handling of listing scenarios.

Update CreateListingModal to use collectionOrderbookKind as fallback for orderbookKind prop
