post-install.sh
Simplifies local development by symlinking exports to the dist directory. 
This allows you to shift the compilation to the integrator during development, enabling fast refresh to work.
Caveats:
Only compatible with the [pnpm file protocol](https://pnpm.io/cli/link#whats-the-difference-between-pnpm-link-and-using-the-file-protocol)
The integrator must integrate [vanilla extract](https://vanilla-extract.style/documentation/integrations/next/)
=> Symlink exports for local development

.github/CODEOWNERS, CODEOWNERS
Moved file to `.github` folder and added `@0xsequence-bot` as first code owner to suppress notifications. Same pattern as in `devops` repo.
https://github.com/0xsequence/devops/blob/master/.github/CODEOWNERS#L5
=> CODEOWNERS, suppress notifications, file location

packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts, packages/sdk/src/react/hooks/useBuyCollectable.tsx, packages/sdk/src/react/hooks/useCancelOrder.tsx, packages/sdk/src/react/hooks/useSell.tsx, packages/sdk/src/react/ui/components/_internals/action-button/ActionButton.tsx, packages/sdk/src/react/ui/components/collectible-card/CollectibleCard.tsx, packages/sdk/src/react/ui/modals/CreateListingModal/_store.ts, packages/sdk/src/react/ui/modals/CreateListingModal/index.tsx, packages/sdk/src/react/ui/modals/MakeOfferModal/_store.ts, packages/sdk/src/react/ui/modals/MakeOfferModal/index.tsx, playgrounds/react-vite/package.json, playgrounds/react-vite/src/lib/MarketplaceContext.tsx, playgrounds/react-vite/src/lib/Settings.tsx, playgrounds/react-vite/src/lib/util/toTitleCaseFromSnakeCase.ts, playgrounds/react-vite/src/tabs/Collectable.tsx, playgrounds/react-vite/src/tabs/Collectables.tsx, playgrounds/react-vite/src/tabs/Debug.tsx, pnpm-lock.yaml
* Pass `TransactionMachine` an `orderbookKind` param to manage making orders for listing and offer for a specific marketplace but `sequence_marketplace_v2`. Set default to `sequence_marketplace_v2`
* Improve styling of playground and add a new cell to tables of offers and listings, `Orderbook`
=> Configure Target Marketplace For Listings and Offers

packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts, packages/sdk/src/react/_internal/transaction-machine/useTransactionMachine.ts, packages/sdk/src/react/hooks/useBuyCollectable.tsx, packages/sdk/src/react/hooks/useCancelOrder.tsx, packages/sdk/src/react/hooks/useCreateListing.tsx, packages/sdk/src/react/hooks/useMakeOffer.tsx, packages/sdk/src/react/hooks/useSell.tsx, packages/sdk/src/react/ui/modals/BuyModal/index.tsx, packages/sdk/src/react/ui/modals/CreateListingModal/_store.ts, packages/sdk/src/react/ui/modals/CreateListingModal/index.tsx, packages/sdk/src/react/ui/modals/MakeOfferModal/_store.ts, packages/sdk/src/react/ui/modals/MakeOfferModal/index.tsx, packages/sdk/src/react/ui/modals/SellModal/index.tsx, packages/sdk/src/react/ui/modals/_internal/components/priceInput/index.tsx, packages/sdk/src/react/ui/modals/_internal/components/switchChainModal/index.tsx, packages/sdk/src/react/ui/modals/_internal/components/transactionDetails/index.tsx, packages/sdk/src/utils/price.ts, playgrounds/react-vite/src/tabs/Collectable.tsx, playgrounds/react-vite/src/tabs/Collectables.tsx
* Improve balance check for making offer, trigger checking it while switching between different currencies,
* Improve switching chain; If connected via Waas, `walletClient.chain.id` isn't useful. So, I moved switching chain functionality outside of Machine while ensuring it's called when modal opens.
* Fix: avoid showing transaction status modal after token approval execution. 
Note that disability and pending states of CTAs may behave weird. I will tackle this issue on another PR
=> Fix .onerror not found and token approval flow

packages/sdk/src/react/ui/modals/BuyModal/Modal.tsx, packages/sdk/src/react/ui/modals/BuyModal/hooks/useBuyCollectable.ts, packages/sdk/src/react/ui/modals/BuyModal/modals/Modal1155.tsx, packages/sdk/src/react/ui/modals/BuyModal/store.ts, packages/sdk/src/react/ui/modals/MakeOfferModal/Modal.tsx, packages/sdk/src/react/ui/modals/_internal/components/priceInput/hooks/usePriceInput.ts, packages/sdk/src/react/ui/modals/_internal/components/quantityInput/index.tsx, packages/sdk/src/react/ui/modals/_internal/components/switchChainModal/index.tsx
This PR is for resolving [this issue](https://github.com/0xsequence/issue-tracker/issues/3098#issuecomment-2592274046) and ([duplicate issue](https://github.com/0xsequence/issue-tracker/issues/3964))
We need to introduce more states for `loading` and `loaded` states of purchase modal to improve ux and unused renders.
=> Refactor buy modal and quantity modal to manage appearance of quantity modal

packages/sdk/src/react/hooks/useCancelTransactionSteps.tsx, packages/sdk/src/react/ui/modals/CreateListingModal/hooks/useTransactionSteps.tsx, packages/sdk/src/react/ui/modals/MakeOfferModal/hooks/useTransactionSteps.tsx, packages/sdk/src/react/ui/modals/SellModal/hooks/useTransactionSteps.tsx, playgrounds/react-vite/src/components/collectible/ListingsTable.tsx, playgrounds/react-vite/src/components/collectible/OffersTable.tsx
Currently we throw errors that are needed to be caught where hooks are used. No need to throw them since we already use `onError` callbacks.
=> Dont throw error if error occurs

packages/sdk/src/react/_internal/api/get-query-client.ts, packages/sdk/src/react/hooks/useCancelTransactionSteps.tsx, packages/sdk/src/react/hooks/useCurrency.tsx, packages/sdk/src/react/provider.tsx, packages/sdk/src/react/ssr/create-ssr-client.ts, packages/sdk/src/react/ui/modals/CreateListingModal/hooks/useTransactionSteps.tsx, packages/sdk/src/react/ui/modals/MakeOfferModal/hooks/useTransactionSteps.tsx, packages/sdk/src/react/ui/modals/SellModal/hooks/useTransactionSteps.tsx, packages/sdk/src/react/ui/modals/TransferModal/_views/enterWalletAddress/useHandleTransfer.tsx, packages/sdk/src/react/ui/modals/_internal/components/transactionStatusModal/index.tsx, playgrounds/react-vite/src/lib/provider.tsx
We weren't able to invalidate queries that subscribed to the query client somehow. Using `MarketplaceQueryClientProvider` fixes it. 
* Refactor transaction execution of transfer modal, remove duplicate implementations
* Set `queriesToInvalidate` to `showTransactionStatusModal` of related transactions `useTransactionSteps`
=> Manage query client state

packages/sdk/src/react/hooks/useCurrencies.tsx
using `toHex` while comparing is misleading, as it converts `0x41e94eb019c0762f9bfcf9fb1e58725bfb0e7582` to `0x307834316539346562303139633037363266396266636639666231653538373235626662306537353832`
=> useCurrencies: replace toHex with Address type for contractAddress filtering

packages/sdk/src/react/ui/modals/CreateListingModal/hooks/useTransactionSteps.tsx, packages/sdk/src/react/ui/modals/MakeOfferModal/hooks/useTransactionSteps.tsx, packages/sdk/src/react/ui/modals/SellModal/hooks/useTransactionSteps.tsx
https://github.com/0xsequence/issue-tracker/issues/4010
We already use `onSuccess` callback on `TransactionStatusModal` , no need to use it in `useTransactionSteps`s of transactions
=> remove duplicate calls of onSuccess in `useTransactionSteps`

packages/sdk/src/react/__tests__/provider.test.tsx, packages/sdk/src/react/_internal/wagmi/__tests__/create-config.test.ts, packages/sdk/src/react/_internal/wagmi/create-config.ts, packages/sdk/src/react/provider.tsx, packages/sdk/src/utils/_internal/error/config.ts, playgrounds/react-vite/src/lib/provider.tsx, playgrounds/react-vite/src/tabs/Collections.tsx
[ISSUE](https://github.com/0xsequence/issue-tracker/issues/4079)
This PR introduces a comprehensive test suite for the createWagmiConfig function, covering both successful and failure scenarios. The tests ensure correct behavior across different wallet configurations and edge cases.
Changes:
•	Added test cases for creating configs with:
•	Empty collections (defaulting to Polygon)
•	Universal wallet setup
•	Embedded wallet setup
•	EIP6963 wallet inclusion/exclusion
•	SSR compatibility
•	Handling missing waasConfigKey (falling back to universal wallet)
•	Added failure cases to ensure proper error handling:
•	Using embedded wallets without a valid waasConfigKey
•	Creating config without walletConnectProjectId
•	Creating config with an empty projectAccessKey
=> 4079 - Add tests for createWagmiConfig

packages/sdk/src/react/hooks/useAutoSelectFeeOption.tsx, packages/sdk/src/react/hooks/useCancelOrder.tsx, packages/sdk/src/react/ui/modals/_internal/components/waasFeeOptionsSelect/WaasFeeOptionsSelect.tsx
Auto selection of fee options for `useCancel` hook didn't involve checking native currency balance, this PR fixes it. 
Also, in `WaasFeeOptionsSelect` component, default selected currency was not applied when it is native currency, it is fixed now.
=> Fix include native currency for auto fee selection

packages/sdk/src/react/ui/components/collectible-card/CollectibleCard.tsx, packages/sdk/src/react/ui/components/collectible-card/Footer.tsx, playgrounds/react-vite/src/tabs/Collectables.tsx, playgrounds/react-vite/src/tabs/components/InfiniteScrollView.tsx, playgrounds/react-vite/src/tabs/components/PaginatedView.tsx
[Issue](https://github.com/0xsequence/issue-tracker/issues/4285)
We forgot to format balance of wallet for tokens with decimals. This PR fixes it and includes some improvements on typings of `CollectibleCard`
For case Sid has encountered, tokenMetadata for ERC1155s had `decimals=2`, which makes `100` -> `1`
=> 4285 - Fix incorrect balance

packages/sdk/src/react/ui/components/collectible-card/Footer.tsx
[Issue](https://github.com/0xsequence/issue-tracker/issues/4306)
use `maxDecimals` on `formatPrice`  to manage overflowing prices
=> 4306 - fix: improve price formatting in collectible card footer

sdk/src/react/ui/modals/BuyModal/Modal.tsx, sdk/src/react/ui/modals/BuyModal/hooks/usePaymentModalParams.ts
Moved the`openSelectPaymentModal` call into a `useEffect` hook to ensure state updates happen after render completion rather than during the render phase. This follows React's best practices for handling side effects and state updates.
=> Fix React state update during render in BuyModal component

playgrounds/shared/src/components/activitiesTable/Body.tsx, sdk/src/react/hooks/useAutoSelectFeeOption.tsx, sdk/src/react/hooks/useCancelOrder.tsx, sdk/src/react/hooks/useCancelTransactionSteps.tsx, sdk/src/react/hooks/util/optimisticCancelUpdates.ts
[Ticket](https://github.com/0xsequence/issue-tracker/issues/4788)
This improves the reliability of query updates following an offer/listing cancellation by ensuring that stale data (like the highest offer or lowest listing) is not shown after a cancel action.
=> Improve query invalidation and refetching after offer/listing cancellation

sdk/src/react/_internal/api/__mocks__/marketplace.msw.ts, sdk/src/react/hooks/__tests__/useCancelTransactionSteps.test.tsx, sdk/src/react/hooks/__tests__/useGenerateCancelTransaction.test.tsx, sdk/src/react/hooks/__tests__/useGenerateListingTransaction.test.tsx, sdk/src/react/hooks/__tests__/useGenerateOfferTransaction.test.tsx, sdk/src/react/hooks/__tests__/useGenerateSellTransaction.test.tsx, sdk/src/react/hooks/useGenerateOfferTransaction.tsx, sdk/src/react/ui/modals/MakeOfferModal/__tests__/Modal.test.tsx, sdk/src/react/ui/modals/_internal/components/actionModal/ActionModal.test.tsx, sdk/src/react/ui/modals/_internal/components/actionModal/ActionModal.tsx, sdk/test/test-utils.tsx
☑️ Non-sequence-wallets - Should make request to GenerateOfferTransaction when mounted, show Approve TOKEN button if there is an approval step, disable Make offer button accordingly,  (_**sdk/src/react/hooks/__tests__/useGenerateOfferTransaction.test.tsx takes care of it**_)
☑️ Sequence Wallets - Should make request to GenerateOfferTransaction when mounted (user is not taking care of token approval) (_**sdk/src/react/hooks/__tests__/useGenerateOfferTransaction.test.tsx takes care of it**_),
☑️  Should handle disability of buttons according to balance sufficiency.
> this feels it belongs to `PriceInput`. We just need to test if it handles its `checkBalance` callback prop ([See updated `PriceInput` tests](https://github.com/0xsequence/marketplace-sdk/pull/291)):  
```
<PriceInput
.... …
```
=> Tests of `OfferModal`

playgrounds/react-vite/src/tabs/Collections.tsx, sdk/src/react/ui/components/collectible-card/__tests__/Media.test.tsx, sdk/src/react/ui/components/collectible-card/media/Media.tsx, sdk/src/react/ui/components/collectible-card/media/types.ts
https://github.com/0xsequence/issue-tracker/issues/5134
Added fallbackContent prop to allow users to specify custom fallback UI when asset loading fails or no assets are provided. Updated tests to verify custom fallback behavior and default to a placeholder image when necessary.
=> Enhance Media component to support custom fallback content

sdk/package.json, sdk/tsdown.config.ts
This patch copies react-day-picker's css file to the dist folder, and adds an export path to the package.json, which allows Vite to successfully import the file during it's SSR build process.
=> Copy and alias react-day-picker css for Vite ssr

playgrounds/react-vite/src/tabs/Collections.tsx, sdk/.changeset/fine-groups-repeat.md, sdk/src/react/ui/components/media/Media.tsx, sdk/src/react/ui/components/media/types.ts
- Added `shouldListenForLoad` prop to the Media component, allowing control over whether to listen for asset load events.
- Updated internal state management to initialize loading based on the new prop.
- Modified event handlers for various asset types to conditionally attach error and load handlers based on the `shouldListenForLoad` prop.
- Updated CollectionCard to set `shouldListenForLoad` to false, preventing load event handling for the displayed media.
=> Enhance Media component to conditionally handle asset loading

sdk/.changeset/early-buckets-call.md, sdk/src/react/hooks/useList1155ShopCardData.tsx, sdk/src/react/ui/components/_internals/action-button/ActionButton.tsx, sdk/src/react/ui/components/_internals/action-button/components/NonOwnerActions.tsx, sdk/src/react/ui/components/marketplace-collectible-card/Footer.tsx, sdk/src/react/ui/components/marketplace-collectible-card/components/ActionButtonWrapper.tsx, sdk/src/react/ui/components/marketplace-collectible-card/types.ts, sdk/src/react/ui/components/marketplace-collectible-card/utils/supplyStatus.ts, sdk/src/react/ui/components/marketplace-collectible-card/variants/ShopCard.tsx, sdk/src/react/ui/modals/BuyModal/components/ERC1155QuantityModal.tsx, sdk/src/react/ui/modals/BuyModal/components/ERC1155ShopModal.tsx, sdk/src/react/ui/modals/BuyModal/store.ts
Show "buy now" action button only when quantityRemaining is greater than zero.
Fixes [this](https://github.com/0xsequence/issue-tracker/issues/5351)
https://github.com/user-attachments/assets/6e12448d-93cd-463d-98cf-a7d500a0a04b
=> fix action button visibility for shop collectible card

sdk/src/react/ui/modals/_internal/components/selectWaasFeeOptions/__tests__/SelectWaasFeeOptions.test.tsx
- **Fee Selection**: Tests selecting different fee options from a dropdown with multiple choices
- **Modal Closing**: Verifies cancel button properly hides modal and triggers callback
- **Fee Confirmation**: Tests confirm button interaction and fee option submission
- **Insufficient Balance**: Ensures confirm button is disabled when user lacks sufficient balance
- **Confirmed State**: Validates UI changes when fee options are confirmed (disabled state, loading indicators)
- **State Management**: Verifies store state is properly reset when modal is closed
=> test: add user interaction tests for SelectWaasFeeOptions component

sdk/.changeset/wise-ties-rest.md, sdk/src/react/ui/components/media/Media.stories.tsx, sdk/src/react/ui/components/media/Media.tsx, sdk/src/react/ui/components/media/types.ts
Will be helpful while fixing [this issue](https://github.com/0xsequence/issue-tracker/issues/5368).
Updated the Media component to replace the className prop with containerClassName and added mediaClassname for better styling flexibility. Adjusted all relevant className usages to ensure consistent application of styles throughout the component.
=> Refactor Media component to use containerClassName and mediaClassname

sdk/src/react/hooks/transactions/useCancelOrder.tsx, sdk/src/react/ui/modals/_internal/components/selectWaasFeeOptions/index.tsx, sdk/src/react/ui/modals/_internal/components/waasFeeOptionsSelect/WaasFeeOptionsSelect.tsx
While trying to sell an item with a WAAS embedded wallet connected, the modal used to automatically select the fees. However, we expect this behavior to be limited only to the ‘cancel’ action. Therefore, I updated the cancel hook. Now, automatic fee selection will no longer occur unless an orderId is provided.
=> Fix avoid auto fee selection

sdk/.changeset/tender-dancers-beg.md, sdk/src/react/ui/modals/TransferModal/_views/enterWalletAddress/_components/TransferButton.tsx, sdk/src/react/ui/modals/TransferModal/index.tsx
https://github.com/0xsequence/issue-tracker/issues/5475
This PR improves the user experience for WaaS transfers by:
- Showing more accurate button states during transfer:
- "Loading fee options" → "Sending transaction" for sponsored transfers
- "Loading fee options" → Fee selection → "Sending transaction" for regular transfers
- Skipping wallet instruction view for WaaS since it's handled in the background
=> Improve WaaS transfer loading states and UX

sdk/.changeset/ninety-houses-sit.md, sdk/src/react/_internal/api/__mocks__/metadata.msw.ts, sdk/src/react/hooks/data/tokens/index.ts, sdk/src/react/hooks/data/tokens/useSearchMintedTokenMetadata.tsx, sdk/src/react/hooks/data/tokens/useSearchTokenMetadata.test.tsx, sdk/src/react/hooks/data/tokens/useSearchTokenMetadata.tsx, sdk/src/react/queries/index.ts, sdk/src/react/queries/searchTokenMetadata.ts
`useSearchTokenMetadata` is for getting metadata of tokens of a items contract with pagination, but it returns metadata of both minted and unminted tokens. So, I implemented [useSearchMintedTokenMetadata](https://github.com/0xsequence/marketplace-sdk/pull/472/commits/609be83f3bdad51a8aaa56810396769bfd944932) as well for exact use case for marketplace app
=> Add `useSearchTokenMetadata` hook

playgrounds/shared/src/components/ERC721SaleControls.tsx, playgrounds/shared/src/components/collections/CollectionCard.tsx, playgrounds/shared/src/components/pages/ShopContent.tsx, sdk/src/react/ui/components/marketplace-collectible-card/variants/ShopCard.tsx
* Fix collectible card image classname to check if either `quantityRemaining` is undefined or it's 0.
* Enhance playground components to work with 1155 sales well.
=> Fix collectible card image opacity

playgrounds/shared/src/components/pages/InventoryPageController.tsx, sdk/src/react/hooks/data/market/useListMarketCardData.tsx, sdk/src/react/queries/inventory.ts, sdk/src/react/queries/listCollectibles.ts, sdk/src/react/ui/components/marketplace-collectible-card/types.ts, sdk/src/react/ui/components/marketplace-collectible-card/variants/MarketCard.tsx
https://github.com/0xsequence/issue-tracker/issues/5637
If user purchased a sale item from a collection that is not set up for marketplace via Builder, we used to not show those tokens in inventory.
This PR is for to show them without any actions user can take, with flag `isTradable`
=> Inventory include shop collections without market setup

sdk/src/react/providers/index.tsx
We have a marketplace query provider in the providers-setup for the Marketplace SDK.
The thought was probably that the consuming app could avoid setting one up, but in practice, this prevents errors from bubbling up, and you most likely want the query boundary to be higher than the SDK anyway
=> Remove usage of marketplace query provider

sdk/src/react/ui/modals/BuyModal/components/ERC1155BuyModal.tsx
We returned null while waiting payment params are loading, while we should have rendered a loading modal instead, between quantity selection and checkout modal state. User could click something else than checkout flow, i.e. click on make offer modal 👇🏼
- Integrated LoadingModal component to display a loading state when payment modal parameters are being fetched.
- This enhancement provides users with visual feedback during the checkout process, improving overall user experience
BEFORE
https://github.com/user-attachments/assets/070cc558-ba2f-4dfe-a840-f63a26eddc1d
AFTER
https://github.com/user-attachments/assets/2f3130a2-6182-4ba0-a62e-4e476ab12ad1
=> Add LoadingModal to ERC1155BuyModal for improved loading state handling

sdk/src/react/ui/modals/_internal/components/calendarDropdown/TimeSelector.tsx, sdk/src/react/ui/modals/_internal/components/calendarDropdown/index.tsx, sdk/src/react/ui/modals/_internal/components/calendarDropdown/overrides.css, sdk/src/styles/index.css, sdk/src/styles/styles.ts
Issue : https://github.com/0xsequence/issue-tracker/issues/5894#issuecomment-3364613180
`overrides.css` was not included in `compile-tailwind.js` script which generates `styles.ts` for and used in shadow root. This PR is to include it in index.css and makes sure it's classes are added to styles.ts as well.
Also, styles of calendar elements polished.
=> Calendar styles
